### ISSUE TITLE
CSOSN 220 não consta no sistema

### ISSUE THREAD

**Issue by Kenzo13** [JonatasFischer/MotorFiscal#1]
O cliente Guilherme das lojas Tatuí recebeu uma nota de um fornecedor, onde a CSOSN veio com um número 220 que não consta no sistema.

**Comment by JonatasFischer** [comment]
Kenzo

Provavelmente a mercadoria em questao é uma mercadoria com CST 20 de origem extrangeira adquirida no mercado interno (2 + 20 0 220) nao consegui encontrar em nenhum local a CSOSN 220.
